# Generated by Django 3.2.5 on 2021-07-29 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_employment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'permissions': (('can_publish', 'Может публиковать'),), 'verbose_name': 'вакансия', 'verbose_name_plural': 'вакансии'},
        ),
    ]
