# Generated by Django 3.2.5 on 2021-07-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_library', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='status',
            field=models.CharField(choices=[('d', 'Draft'), ('p', 'Published'), ('w', 'Withdrawn')], max_length=1, null=True),
        ),
    ]
