# Generated by Django 3.2.5 on 2021-07-22 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_library', '0004_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='bublicationdata',
            new_name='publication_data',
        ),
    ]
