# Generated by Django 3.2.5 on 2021-07-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_library', '0006_auto_20210722_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='country',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
