# Generated by Django 3.2.5 on 2021-07-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_library', '0007_author_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='status',
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('d', 'Draft'), ('p', 'Published'), ('w', 'Withdrawn')], default='d', max_length=1),
        ),
    ]
