# Generated by Django 3.2.5 on 2021-07-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_library', '0008_auto_20210722_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('d', 'Draft'), ('r', 'Review'), ('p', 'Published')], default='d', max_length=1),
        ),
    ]
